version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      -"8000:8000"
    volumes:
      - .:/gcptest
  nginx:
    image: nginx:latest
    ports:
      -"80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf
    depends_on:
      - web